### ISSUE TITLE
Todo (PR welcome)

### ISSUE THREAD

**Issue by greyli** [helloflask/bootstrap-flask#50]
- [ ] #229
- [ ] #230
- [ ] #231

Done

- [x] Host a live demo of the example application.
- [x] Improve `render_icon` to use CSS icon (Is it needed? The current implementation is using SVG sprite).
- [x] **Improve the display of table action buttons (the delete icon is not in line with others).**
- [x] Add warning if Flask-WTF not installed when using `render_table` actions.
- [x] Support to add custom action button.
- [x] Move builds to GitHub Action.
- [x] Add render test for every input and form type.
- [x] Add doc for configuration options.
- [x] Add config var to set default form submit button class: size, style, outline, etc. Maybe use `BOOTSTRAP_FORM_BTN_SIZE`,  `BOOTSTRAP_FORM_BTN_STYLE`, `BOOTSTRAP_FORM_BTN_OUTLINE`, `BOOTSTRAP_FORM_BTN_BLOCK`.

**Comment by greyli** [comment]
Moved to `TODO.md`.

**Comment by caffeinatedMike** [comment]
@greyli #134 opened to add custom action buttons to `render_table` macro 😄
